defaults: &defaults
  adapter: postgresql
  template: template0
  encoding: UTF8

development:
  <<: *defaults
  database: app_development

test: &tests
  <<: *defaults
  database: app_test
  
production:
  <<: *defaults
  database: app_production

cucumber:
  <<: *tests
